- name: mariadbをインストール
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python
    - mariadb
    - mariadb-server
    - libselinux-python

- name: 自動起動設定
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Rootユーザーの作成
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes

- name: wordpressのデータベースを作成
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: wordpress
    state: present

- name: wordpressユーザーを作成し,wordpressのデータベースに全ての権限を付与 
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: wordpress
    password: "{{ mysql_db_password }}"
    priv: "wordpress.*:ALL"
    host: localhost
    state: present