- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Change hostname
  hostname:
    name: "{{ HostName }}"

- name: Add EPEL repository
  shell: creates=/etc/yum.repos.d/epel.repo yum install -y epel-release

- name: Add Remi repository
  command: rpm -Uivh --replacepkgs http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: yum update
  yum:
    name: "*"
    state: latest

- name: Install basic packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - ruby-devel
    - readline-devel
    - ncurses-devel
    - gdbm-devel
    - openssl-devel
    - libxslt-devel
    - sqlite-devel
    - libyaml
    - libyaml-devel
    - tcl-devel
    - libffi-devel
    - gcc
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - vim
    - zsh
    - tree
    - wget

- name: Install Development Tool
  yum:
    name: "@Development tools"
    state: latest