- name: download wordpress
  get_url:
    url="https://wordpress.org/latest.tar.gz"
    dest=/tmp/wordpress.tar.gz

- name: unpack wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no

- name: change wordpress's owner to nginx
  file:
    path: /var/www/wordpress
    owner: nginx 
    group: nginx
    recurse: yes

- name: restart nginx
  service:
    name: nginx 
    state: restarted
