- name: install php-fpm-70
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: remi,remi-php70
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-mbstring
    - php-pdo
    - php-mcrypt
    - php-mysqlnd
    - php-opcache
    - php-xml

- name: change listen
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "listen = 127.0.0.1:9000"
    replace: "listen = /var/run/php7-fpm.sock"

- name: change user
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "user = apache"
    replace: "user = nginx"

- name: change group
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "group = apache"
    replace: "group = nginx"

- name: uncomment listen.owner
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: ";listen.owner = nobody"
    replace: "listen.owner = nginx"

- name: uncomment listen.group
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: ";listen.group = nobody"
    replace: "listen.group = nginx"

- name: uncomment listen.owner
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: ";listen.mode = 0660"
    replace: "listen.mode = 0660"

- name: Automatic load when boot
  service:
    name: php-fpm
    enabled: yes

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted