- name: php-fpm-70をインストール
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: remi,remi-php70
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-mbstring
    - php-pdo
    - php-mcrypt
    - php-mysqlnd
    - php-opcache
    - php-xml

- name: listenをソケットに変更
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "listen = 127.0.0.1:9000"
    replace: "listen = /var/run/php7-fpm.sock"

- name: Nginxユーザーに変更
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "user = apache"
    replace: "user = nginx"

- name: Nginxグループに変更
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: "group = apache"
    replace: "group = nginx"

- name: listen.ownerのコメントアウトを解除
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: ";listen.owner = nobody"
    replace: "listen.owner = nginx"

- name: listen.groupのコメントアウトを解除
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: ";listen.group = nobody"
    replace: "listen.group = nginx"

- name: listen.modeのコメントアウトを解除
  replace:
    dest: /etc/php-fpm.d/www.conf
    regexp: ";listen.mode = 0660"
    replace: "listen.mode = 0660"

- name: 自動起動設定
  service:
    name: php-fpm
    enabled: yes

- name: php-fpmを再起動
  service:
    name: php-fpm
    state: restarted