- name: certbotをインストール
  yum:
    name: certbot
    state: latest

- name: 証明書を取得
  command: certbot certonly --standalone -d {{ HostName }} -w /var/www/html --email {{ Email }} --agree-tos --keep-until-expiring --non-interactive

- name: 証明書の自動更新設定
  cron:
    name: certbot
    cron_file: certbot
    user: root
    special_time: daily
    job: sh -c 'certbot renew && /usr/sbin/service nginx reload' >> /var/log/certbot/cron.log